export default {
    // bgImage: require('../assets/images/initialScreen.png'),
    bgLogo: require('../assets/images/logo.png'),
    icLogo: require('../assets/images/eatmore-logo.png'),
    icShow: require('../assets/images/show.png'),
    icHide: require('../assets/images/hide.png'),
    icUserLogo: require('../assets/images/user.png'),
    icSearch: require('../assets/images/search.png'),
    icHome: require('../assets/images/home.png'),
    icCart: require('../assets/images/cart.png'),
    icSubscription: require('../assets/images/subscription.png'),
    icUserProfileLogo: require('../assets/images/user-profile-logo.png'),
    icSearchItem: require('../assets/images/search-bar.png'),
    icPizzaItem: require('../assets/images/pizza.png'),
    icBurgerItem: require('../assets/images/burger.png'),
    icBurgerTop: require('../assets/images/burger-item.png'),
    icPlusIcon: require('../assets/images/plus-icon.png'),
    icBack: require('../assets/images/icBack.png'),
    icBurgerLarge: require('../assets/images/large-burger.png'),
    icPLus: require('../assets/images/plus.png'),
    icMinus: require('../assets/images/minus.png'),
    icDeleteCart: require('../assets/images/delete-img.png'),
    icCartBurger: require('../assets/images/cart-burger.png'),
    icPaymentArrow: require('../assets/images/right-arrow.png'),
    icDoneImg: require('../assets/images/done-img.png'),
    icSubBurger: require('../assets/images/sub-burger.png'),
    icSubPizza: require('../assets/images/sub-pizza.png'),
    icUserImg: require('../assets/images/user-img.png'),
}